name: Deploy Frontend to Vercel

on:
  push:
    branches: [ develop ]
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: frontend 

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Pull Vercel project settings
        run: |
          vercel link --project ${{ secrets.VERCEL_PROJECT_ID }} --token ${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        run: |
          npx vercel --prod -y --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}